# SPDX-FileCopyrightText: 2026 Oggvik
# SPDX-License-Identifier: AGPL-3.0-or-later

modLoader = "javafml"
loaderVersion = "[36,)"
issueTrackerURL = "https://github.com/oggvik/stop-minimizing-on-focus-loss-mc/issues"
license = "AGPL-3.0-or-later"

[[mods]]
modId = "fullscreen_tweaks"
version = "${file.jarVersion}"
displayName = "Fullscreen Tweaks"
displayURL = "https://github.com/oggvik/stop-minimizing-on-focus-loss-mc"
authors = "Oggvik"
logoFile = "icon.png"
description = '''
Customizes Minecraft fullscreen and window behavior, including focus-loss and loading-screen controls where supported.
'''

[["dependencies.fullscreen_tweaks"]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "CLIENT"

[["dependencies.fullscreen_tweaks"]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5]"
ordering = "NONE"
side = "CLIENT"
