# SPDX-FileCopyrightText: 2026 Oggvik
# SPDX-License-Identifier: AGPL-3.0-or-later

modstitch.platform=moddevgradle

mcVersion=26.3

deps.neoforge=26.3.0.8-beta

meta.mcDep=[26.3,26.4)
pub.stableMC=26.3

# Minecraft no longer auto-minimizes its SDL3 fullscreen window on focus loss.
templateNoop=true
